name: space
description: Everyone has their own unique space.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+2

environment:
  sdk: '>=3.0.0 <3.22.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_spinkit: ^5.2.0
  rive: ^0.9.1
  graphic: ^2.2.1
  quiver: ^3.2.1
  intl: ^0.19.0
  provider: ^6.1.2
  equatable: ^2.0.5 #测试bloc用

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.5
  scaled_app: ^2.3.0 #屏幕适配
  fluttertoast: ^8.1.2

 # 这里是独立出来的包
  l10n:
    path: packages/l10n
  utils:
    path: packages/utils
  anim:
    path: packages/anim
  generativeartistry:
    path: packages/generativeartistry
#  echart:
#    path: packages/echart

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  lottie: 2.7.0
  shimmer: 3.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/anim_lottie/
    - assets/anim/login_screen_character.riv