name: space
description: Everyone has their own unique space.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_spinkit: ^5.2.0
  rive: ^0.9.1 # riv动画


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  lottie: 2.7.0
  shimmer: 3.0.0


flutter:

  uses-material-design: true
  assets:
    - assets/icons/
    - assets/anim_lottie/
    - assets/anim/login_screen_character.riv